### PR TITLE
Add alaska gem

### PR DESCRIPTION
**Pull request by diclophis**
In contrast to the default execjs runtime, the alaska runtime constructs a persistent pipeline to the nodejs interepreter, greatly reducing roundtrip time of coffeescript compliation.

### CODE REVIEW

**Comment by hothero** [comment]
alaska can work on rails4 projects? and could you have the benchmark?

**Comment by diclophis** [comment]
@hothero RE: rails4 compatibility, absolutely this gem works with both rails3/rails4

In terms of benchmarks, see below:

### COUNT OF NON-SPEC COFFEESCRIPT FILES

	$ find app/ -name "*.coffee" | grep -v spec | wc -l
     
     791

### PRECOMPILE WITHOUT ALASKA

	$ time bundle exec rake assets:clobber assets:precompile
	I, [2015-09-28T11:57:49.422266 #49115]  INFO -- : Removed /Users/mavenlink/workspace/mavenlink/public/compiled
	rm -rf /Users/mavenlink/workspace/mavenlink/tmp/cache/assets
	I, [2015-09-28T11:57:52.431264 #49115]  INFO -- : Writing /Users/mavenlink/workspace/mavenlink/public/compiled/admin-84ba9df7fe291829fd73d978351dff807574d356b8f9422832481efaef199f37.css
	 ... more output of written compiled assets similar to the above line
	
	real    4m5.384s
	user    3m11.180s
	sys     0m48.441s

### PRECOMPILE WITH ALASKA

	$ time bundle exec rake assets:clobber assets:precompile
	I, [2015-09-28T11:40:12.238647 #48881]  INFO -- : Removed /Users/mavenlink/workspace/mavenlink/public/compiled
	rm -rf /Users/mavenlink/workspace/mavenlink/tmp/cache/assets
	Listening on port /var/folders/78/78nk9v410f99npdwy_pxwfbw0000gn/T/alaska20150928-48881-hafa5b
	alaska.js started
	I, [2015-09-28T11:40:15.549393 #48881]  INFO -- : Writing /Users/mavenlink/workspace/mavenlink/public/compiled/admin-84ba9df7fe291829fd73d978351dff807574d356b8f9422832481efaef199f37.css
     ... more output of written compiled assets similar to the above line
    
	real    2m10.534s
	user    1m35.053s
	sys     0m21.143s


On rails3 the difference in our application was even more dramatic (down to 2m from 10m). If a application has less than 100 `.coffee` files, I imagine the performance increase will be negligible. The key advantage the alaska gem provides is that is "re-uses" a single `/usr/bin/node` process, instead of starting a new process for each `.coffee` file to compile... basically the classic `CGI` vs. `FCGI` problem. Also it helps with development because without alaska our application would "timeout" and require several reloads on fresh branch in development because the default pipeline would just ham up trying to get everything compiled.

I am not certain exactly how to express this benchmark data in terms of a "single sentence" description for the gem... there are more details of course in the gems README.md

**Comment by diclophis** [comment]
@hothero any chance you could review this PR, I have corrected the merge conflict (by adding a new section to the bottom) and updated the gems docs to indicate that its compatible with both rails3/rails4

**Comment by hothero** [comment]
cool. Could you just do one more step to add build status from TravisCI?? I think you have some tests. It would be good.

**Comment by diclophis** [comment]
Ok, got it added, and its good-to-go: https://travis-ci.org/mavenlink/alaska

**Comment by diclophis** [comment]
Many thanks

**Pull request merged**
