### PR TITLE
Add knock gem to user section

### PR DESCRIPTION
**Pull request by nsarno**
I added the knock gem. Knock is a lightweight authentication solution based on JWT for rails API-only applications. It is already in [awesome-ruby](https://github.com/markets/awesome-ruby), but it definitely belongs here as well!

Cheers!

### CODE REVIEW

**Comment by hothero** [comment]
Awesome, could you help us to fix conflict?

**Comment by nsarno** [comment]
Done! :)

**Comment by hothero** [comment]
Thanks. But I think knock should be in API section.

**Comment by nsarno** [comment]
Knock is an authentication solution and it works with non-api applications even if it is designed with APIs in mind. I think someone looking for a solution like Knock would look for it under the Authentication section before the API one.

**Comment by hothero** [comment]
I know what you mean after carefully go through the README. Thanks for your contribution !!

**Comment by nsarno** [comment]
🎉

**Pull request merged**
