### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zedtux**
Adds the fortress gem to the Authorization section

### CODE REVIEW

**Comment by zedtux** [comment]
@hothero what's the problem with this PR?

**Comment by zedtux** [comment]
Hello World

**Comment by zedtux** [comment]
@hothero, are you HOT for merging this ?

**Comment by hothero** [comment]
@zedtux hello, this one has been migrated to gitlab. Behind this, the latest commit is 3 years ago...we need the repo is still on maintaining

**Comment by zedtux** [comment]
Well, sure, I can change the URL, and yeah, but this PR is old too 😄.

Anyways, the fortress plugin is stable and I don't see what I can change in it... I could update the `README.md` file if you like it 😆

**Pull request closed without merging**
